### ISSUE TITLE
Client Crashing

### ISSUE THREAD

**Issue by Minners** [Lubenica98/FairPlayMinecraft#106]
When i try to Verify me on the server it say this: http://prntscr.com/fyodu3

**Comment by Lubenica98** [comment]
Can you please run the application using the "-debug" parameter? Open the CMD in the same folder where FPMC.exe is located at and execute "FPMC.exe -debug" (without the quote marks). A console will pop up. Please copy ALL content of the console which will pop up and send it to me here.
Thanks!
