### ISSUE TITLE
[Linux] Client dont work

### ISSUE THREAD

**Issue by WolverinDEV** [Lubenica98/FairPlayMinecraft#108]
Well in this issue i think the title dont says everythink :D 
Well i will explain what i mean.

I joined you test-server and downloaded the client from https://www.spigotmc.org/resources/fairplayminecraft-linux.33938/.
After that i change the file permissions to -rwxrwxr-x. (So anybody can execute this file)
I executed this file (as non root, and as root as well (i tried)) and it shows up ```Please Wait``` and closed after a second. If im running this in GDB the its says after the Please Wait dialog that cheats are not allowed, but i joined with a vanilla Minecraft 1.12 Client

**Comment by Lubenica98** [comment]
Working on that (see #91)

**Comment by Lubenica98** [comment]
Fixed in version 1.0.0
