### ISSUE TITLE
Il file non funzione. Aiuto! (windows 7)

### ISSUE THREAD

**Issue by bigpoggi** [Lubenica98/FairPlayMinecraft#116]
Ciao. Ho comprato il plugin, messo nella cartella /plugins del mio server, e riavviato. Funziona tutto alla perfezione, il guaio è che quando un player entra sul server, scarica il file e lo avvia il progtamma dice che bisogna collegarsi al server e dopo eseguire il programma (anche se il player ha già eseguito il programma mentre era nel server.) Aiutatemi!

**Comment by Lubenica98** [comment]
English please?

**Comment by bigpoggi** [comment]
Hello. I bought the plugin, placed in my / server's folder / plugins, and restarted. It works all in perfection, the trouble is that when a player enters the server, download the file and start it, it says you have to connect to the server and run the program (even if the player has already run the program while on the server. ) Help me!

**Comment by Lubenica98** [comment]
Which plugin version are you running?

**Comment by bigpoggi** [comment]
the plugin is in the latest version

**Comment by Lubenica98** [comment]
You have to use that application version then: https://bitbucket.org/Lubenica98/fairplayminecraft/downloads/FPMC_win_BETA.exe

**Comment by bigpoggi** [comment]
wow, function, endless thanks! I'm really proud of it. Can you give me beta versions for linux and mac os too? Thanks Again

**Comment by Lubenica98** [comment]
Soon the 6.0.0 will no longer be beta, but stable so then will the apps for linux and mac be updated. This or maybe next week.

**Comment by bigpoggi** [comment]
Thanks so much. Can you add a comment when it happens? Thank you

**Comment by Lubenica98** [comment]
You will be notified on spigot website when an update comes out
