### ISSUE TITLE
 fpmc check does not work correctly!

### ISSUE THREAD

**Issue by d4d3boss** [Lubenica98/FairPlayMinecraft#118]
Version: 6.0.0 BETA 2

When executing the command, the player is blocked but no message appears.

Also when you start the application (while the player is locked with fpmc check) says that you need to be connected to the server

**Comment by Lubenica98** [comment]
Please attach your config.yml file. Also, are you running bungeecord?

**Comment by d4d3boss** [comment]
I've reset my config several times

Yes, I use bungeecord

Config:

https://hastebin.com/amefitekal.coffeescript

**Comment by Lubenica98** [comment]
Can you also give me the plugin's config.yml file which is installed on the Bungee side?

**Comment by d4d3boss** [comment]
Sure,

https://hastebin.com/wosaqupazo.coffeescript

The bungeecord config did not touch it

**Comment by Lubenica98** [comment]
Thank you very much! Will be fixed in the next version :)

**Comment by d4d3boss** [comment]
Thank you for your support :)

**Comment by Lubenica98** [comment]
You're welcome :)
