### ISSUE TITLE
Add HWID Checks and Directory Saving (Also, solution to inject clients)

### ISSUE THREAD

**Issue by 1002511** [Lubenica98/FairPlayMinecraft#123]
**HWID CHECKS:** The thing I see hackers do the most is use a VPN and log on with different IP addresses. The solution is add a check when the application runs to obtain the computer's HWID, and ID for every hardware version. Unlike IP, the HWID can't be changed. Make it so when someone gets banned, it tags to their HWID. It acts as an IP Ban, but it is not bypassable. 

**DIRECTORY SAVING:** When the application runs, the files inside of the .minecraft/versions and .minecraft/mods should be returned and saved on the Minecraft server. Therefore, someone can do /fpmc directories <nickname> <mods/versions/all>

**SOLUTION TO INJECT CLIENTS:** Make an application version where the application is always running, and it occashunally (spelling 1/10) checks if any applications with no name or include "Vape" or "Ghost", they would run the cheat commands in the config. If the player closes the application, they get kicked from the server. When they connect to it again, they have to have the application open and then they are free to move around. If the player closes Minecraft, this version of FPMC closes as well.

_Thanks for letting me request these features! The plugin looks great so far, but adding these things will make it better! Good luck!_

**Comment by Lubenica98** [comment]
Hello,

The first feature is already on the list (#85) and will be added sometime soon. As for the second request, seeing which mods player is using is a feature that is also already on the list (#97) and will be added. I don't see any point in saving directory names in of all the versions. The system checks only the version that player is currently running, I don't see why it would bother with other directories if they are not in use.
The third request is also somehow on the list, I am working on that.

Thanks for the requests!
