### ISSUE TITLE
error

### ISSUE THREAD

**Issue by b81114** [Lubenica98/FairPlayMinecraft#133]
![image](https://user-images.githubusercontent.com/33824414/33006705-5ca7e3dc-ce06-11e7-91f4-bd4989952da8.png)

**Comment by Lubenica98** [comment]
Please try this version: https://bitbucket.org/Lubenica98/fairplayminecraft/downloads/FPMC_win_beta.exe

**Comment by b81114** [comment]
this version no error
thank you
