### ISSUE TITLE
Detect ghost clients...

### ISSUE THREAD

**Issue by 1002511** [Lubenica98/FairPlayMinecraft#142]
Hey! I have a problem with people bypassing FPMC with ghost clients, such as vape. Here’s how to check for ghost clients:

A quick way you can check for ghost clients is to check recent java strings. I found this video on YouTube that has a download link to a text file with 30+ strings. Here it is: https://youtu.be/gtAYfpcm73c

Also, not to mention, you can see whether or not any folders in .minecraft, downloads, or Skype Recorved Files have been modified 

I would appreciate if you did something about this. Thanks! :D

**Comment by Lubenica98** [comment]
Ghost client check has been implemented in the upcoming version which will be released this month as a beta.

**Comment by Lubenica98** [comment]
Added in the upcoming version.
