### ISSUE TITLE
Application does not work with Bungeecord

### ISSUE THREAD

**Issue by d4d3boss** [Lubenica98/FairPlayMinecraft#145]
When I try to enter a sub-server connected to the bungeecord, even if the application is in the background it is not detected

**Comment by Lubenica98** [comment]
Are you running the beta version of the plugin?

**Comment by d4d3boss** [comment]
Yes

**Comment by d4d3boss** [comment]
I wanted to try the hardware id ban, I saw that with the old application works .. with the new app no

**Comment by d4d3boss** [comment]
Is it a plugin problem?

**Comment by d4d3boss** [comment]
News?

**Comment by Lubenica98** [comment]
Yes, it is a plugin problem.
Thank you for the report, I will look into this and update the status here.

**Comment by d4d3boss** [comment]
Are there any news?

**Comment by Lubenica98** [comment]
Fixed in the upcoming version. Will be released in the following week.
