### ISSUE TITLE
Untrusted Executable

### ISSUE THREAD

**Issue by decontamin4t0R** [Lubenica98/FairPlayMinecraft#46]
Hello,

I think that some very security-aware users of minecraft have the problem that they should run an executable which is neither from a trusted source nor verifyable with a source code (or decompile)

I think that atleast the executable should be open-source.

Edit: AND that it is signed with a self-signed certificate

**Comment by Lubenica98** [comment]
Hello,
The application won't be open-source as it would be then possible for someone to make a version of it which always says that the user is not using cheats, even if it is. Furthermore, I think that open sourcing the application won't have any good for most of the players using it as (at least in my country when I had a server), most of them are not familiar with programming so it won't have any sense for them looking into the code.

**Comment by decontamin4t0R** [comment]
Yes, I understand the problem of the false version, although I think this is a problem.
I dont know how to solve this problem without open-sourcing.
