### ISSUE TITLE
program isssue

### ISSUE THREAD

**Issue by arturek1666** [Lubenica98/FairPlayMinecraft#68]
This is what i get :)
![image](https://cloud.githubusercontent.com/assets/1558228/22857744/bf702124-f0a2-11e6-8316-be9cb0a70fab.png)

**Comment by Lubenica98** [comment]
Hello,
Please run the application using parameter "-debug" (without the quotation marks) - open cmd in the folder where FPMC.exe is located and run it using "FPMC.exe -debug" (without the quotation marks). A console will pop up. When the error above shows, screenshot the last content of the console.
Thanks!

**Comment by arturek1666** [comment]
![image](https://cloud.githubusercontent.com/assets/1558228/22857808/bc131caa-f0a4-11e6-97b4-14c6fd2f8372.png)

**Comment by arturek1666** [comment]
![image](https://cloud.githubusercontent.com/assets/1558228/22857816/d594d790-f0a4-11e6-9859-5efc27029bd6.png)

**Comment by arturek1666** [comment]
Oo wait maby it's becouse it's forge 1.11.2 xD not 1.11

**Comment by Lubenica98** [comment]
Do you perhaps have Forge filter enabled in your config?

**Comment by arturek1666** [comment]
yes

**Comment by arturek1666** [comment]
and little loader as well

**Comment by Lubenica98** [comment]
Can you give me your filter files please?

**Comment by arturek1666** [comment]
Eh file is not supported give me a sec

**Comment by arturek1666** [comment]
[files.zip](https://github.com/Lubenica98/FairPlayMinecraft/files/768976/files.zip)

**Comment by arturek1666** [comment]
I switch of those settings to
use_filter_for_forge: false
use_filter_for_liteloader: false
and still same error with the software

**Comment by Lubenica98** [comment]
Please try the latest application version (5.4.0). It it still doesn't work, run it again with the debug parameter.

**Comment by arturek1666** [comment]
Works nice what was wrong than?

**Comment by arturek1666** [comment]
I switched 
use_filter_for_forge: true
use_filter_for_liteloader: true
and that error goes again

**Comment by Lubenica98** [comment]
Please give me the screenshot of the console when you run it with the debug parameter.

**Comment by arturek1666** [comment]
![image](https://cloud.githubusercontent.com/assets/1558228/22858301/1041f858-f0b1-11e6-80e0-51928124b9ff.png)

**Comment by arturek1666** [comment]
I think i know why this might be a reason. So minecraft launcher supports installing in different  directory for me i have mods installed in D drive as i have mods for 1.11 than 1.10 than 1.7 and because of that all of them are in different directory.

**Comment by arturek1666** [comment]
Yes it's 100% the reason now so I install minecraft mod in .minecraft and it works but when my minecraft files are in deferent directory it will not work

**Comment by Lubenica98** [comment]
So you have Minecraft installed in AppData\Roaming\.minecraft folder, but mods are somewhere else?

**Comment by arturek1666** [comment]
No, let me show you in screenshot xD. 
![image](https://cloud.githubusercontent.com/assets/1558228/23026461/3ad017b6-f459-11e6-9c18-643b28a0a01b.png)

**Comment by arturek1666** [comment]
![image](https://cloud.githubusercontent.com/assets/1558228/23026513/67d30f20-f459-11e6-9a5b-fd4926fd1523.png)

**Comment by arturek1666** [comment]
That's what my .minecraft has xD
![image](https://cloud.githubusercontent.com/assets/1558228/23026624/c0d3ed7e-f459-11e6-9154-672add8bb627.png)
