### ISSUE TITLE
Add support for other directory 

### ISSUE THREAD

**Issue by arturek1666** [Lubenica98/FairPlayMinecraft#80]
I already post this in here but it was removed but I wasn't fixed and wasn't explain why removed it and not fixed so i am writing this again xD

The app error:
![image](https://cloud.githubusercontent.com/assets/1558228/23587894/0d2ac8c2-01ad-11e7-9a65-6843c9d89a96.png)

Console log:
![image](https://cloud.githubusercontent.com/assets/1558228/23587899/1ffa92fc-01ad-11e7-869b-0f9ea3a22e04.png)

Minecraft directory LOG
![image](https://cloud.githubusercontent.com/assets/1558228/23587902/38a13482-01ad-11e7-9761-2d4082f90606.png)

How you can see because i have mods installed in other directory it doesn't not work and crashes the launcher. If you can't fix it you should inform that this is not fixable and than close.

**Comment by Lubenica98** [comment]
Hello,
The last report was closed and marked as solved, but I don't know why you are still having this issue. I will look into this today and I'll get back to you.

**Comment by Lubenica98** [comment]
Please try the latest 5.4.4 application version and report back.
Thanks!

**Comment by arturek1666** [comment]
Goood job looks like it's working good :) Thx. one more thing can you add so you can add multiple stuff to filter not just one?

**Comment by arturek1666** [comment]
I have issue that I added all mods to list but it kicks me still i will try to fix it my self maby i am doing something wrong xD

**Comment by arturek1666** [comment]
OK somehow it work's but when added all mods to forge_filter it still say you have mods installed that are not allowed.

**Comment by arturek1666** [comment]
Ok I had notice that when i had no mods only folder in mods folder it say I have cheats and can't join after removing folders in mods folder i was able to join xD LOL

**Comment by arturek1666** [comment]
It thinks that folders are mods I think LOL there is no other explanation

**Comment by Lubenica98** [comment]
Sorry, I don't understand what problem are you having. This issue has been solved so I will mark this as solved. If you have any other issue please open another issue or contact me on Spigot.

**Comment by arturek1666** [comment]
The best way to show you is in video and. I wll give you in a sec in private message on spigot.
