### ISSUE TITLE
Check Dont work!

### ISSUE THREAD

**Issue by Minners** [Lubenica98/FairPlayMinecraft#88]
When i open the Client it say i must join first a server but i am already on the server
using with Bungeecord

http://prntscr.com/ey7jh5 - Screen Shot from MC and FPMC Client!
https://hastebin.com/kafubawide.coffeescript - Config (IP's Hidden) [IP's are right configured]

**Comment by Lubenica98** [comment]
Which plugin version are you using?

**Comment by Minners** [comment]
the newest

**Comment by Minners** [comment]
5.8.0 BETA 3

**Comment by Minners** [comment]
i have updated it to the newest (5.8.0) its not working i dont know why wich ports needs the plugin? enventually the ports are blocked?
i know only this port 11414 this port is free

**Comment by Lubenica98** [comment]
Be sure you are running the **5.8.0** plugin version and **5.4.7** application version.
Are you running BungeeCord?

**Comment by Minners** [comment]
yes we have bungeecord (plugin is also on the bungeecord istalled)

**Comment by Lubenica98** [comment]
Can you give me your config file? The one you gave me is blank

**Comment by Minners** [comment]
okay with the newest version it works the Client dindt updated!
