### ISSUE TITLE
Can't join demo server

### ISSUE THREAD

**Issue by TheBlackDev** [Lubenica98/FairPlayMinecraft#89]
Escuse me but the demo server is whitelisted. Can you disable it or whitelist this account : TheBlackDev_
Thanks in advance,
TheBlackDev_
![image](https://cloud.githubusercontent.com/assets/26929589/25177798/73017e56-2503-11e7-9ee8-0f763eb0c018.png)

**Comment by Lubenica98** [comment]
Sorry about that, the reason why the test server is whitelisted is because the BETA version is currently being tested on it. The BETA version will become stable version today so I will remove the whitelist then.

**Comment by Lubenica98** [comment]
Disabled whitelist!
