### ISSUE TITLE
Virus Total

### ISSUE THREAD

**Issue by Chenguang1** [Lubenica98/FairPlayMinecraft#92]
Hello, as you said:
> If your antivirus software flags it as a virus, please contact me so I can report the false-positive to the antivirus software company.

So, I'm contacting you. Here is virustotal result:
https://www.virustotal.com/en/file/c42f7eeafaf01b4a71bc06c901f4db9589e54367d17aafdaaf1c2b38f3c1b694/analysis/1495777720/
2/62

**Comment by Lubenica98** [comment]
Hello,
Thank you for the report! I have reported the false-positive to both companies.
