### ISSUE TITLE
Disabled Forge support to block ghost clients.

### ISSUE THREAD

**Issue by Chenguang1** [Lubenica98/FairPlayMinecraft#95]
Hello! I'm looking for a decent anti-cheat for my vanilla (spigot 1.11.2) server. I like the idea of client-side check so I'm considering of buying FPMC. However, I need to make sure it works as it should and it's not just some kind of placebo.
The author of this video https://www.youtube.com/watch?v=IKRPwMOVTSA says that the official test server of FPMC 89.34.96.15:25589 is not protected very good and he demonstrates it. I've seen your conversation in a spigot comment section and I want to ask you: was the Forge support disabled when he made the video? Is this support disabled right now? If so I wanna ask him to test the server again.

**Comment by Lubenica98** [comment]
Hello,
I'm not sure what were the settings when he tested that, but forge filter is now disabled on the test server.

**Comment by Chenguang1** [comment]
Lubenica98, I should say that VirusTotal is not complaining anymore about FPMC_win.exe file. 0/61. No false positives.

In addition, thank you for disabling Forge support. Unfortunately, it seems like it's possible to enter your server with a hacked client (Skillclient particularly): https://imgur.com/Au9DiXW
You can check comments under the video I mentioned earlier.

**Comment by Lubenica98** [comment]
Hm, I couldn't join using that client: https://image.prntscr.com/image/Pg08fAuvRkSZxAwK6y48-g.png
Can you please run the application using the "-debug" parameter? Open CMD in the folder where FPMC.exe is located at and type in "FPMC.exe -debug". A console will pop up. Please send me the content of the console.
Thanks!
